### ISSUE TITLE
Slope/Staircase Support

### ISSUE THREAD

**Issue by GoodErnest64** [ColormaticStudios/quality-godot-first-person-2#10]
does this addon support staircases or am I doing something wrong ?

**Comment by ColormaticStudios** [comment]
I need to do some testing. I haven't implemented any code that does something like that, what is the desireable behavior?

**Comment by roberto-urbani23** [comment]
In the character inspector, since it's extending CharacterBody3D, you can uncheck **Stop on Slope** and set the max angle to **89** (for some reasons, 90 will make the player stuck). Also **Snap Length** to 1 otherwise your character will not remain attached to stairs if you sprint while going downstairs

**Comment by CZakarya** [comment]
I should add that to the README
