### ISSUE TITLE
Jolt Physics break Crouching

### ISSUE THREAD

**Issue by HakanBacon** [ColormaticStudios/quality-godot-first-person-2#24]
I've been working on a game that controls like Amnesia for some time and I used this amazing template to create the player controls around it. It worked flawlessly, but since my game is based around physics interactions, I needed a better solution, and that is Jolt.

And well....it didn't go well. The physics are messing with the crouching mechanic (see video). The crouching animation restarts over and over again until I somehow manage to break free. I tried going back to the default physics and oh man....the framerates are dead. But crouching works flawlessly lol

https://github.com/user-attachments/assets/dd87e9d0-414e-4213-939d-df6bfaacc6ac

**Comment by CZakarya** [comment]
This seems to be a bug with Jolt, we've seen this before with version one. I don't think Jolt likes having the collision shape scaled, because if you remove scaling from the crouch animation, the problem magically vanishes. This may be something to report to Jolt developers. For now, there may be a way to switch between crouching and standing collision shapes so scaling isn't necessary.

**Comment by HakanBacon** [comment]
Hmm since this isn't an issue with this repository I'll close this issue. But thanks!

**Comment by HakanBacon** [comment]
For those peeps coming back to see this, my solution was pretty simple:

give your CharacterBody3D two colliders, one for standing and one for crouching. Enable and disable those accordingly. You can even do that in the Animation node itself
